#!/usr/bin/env bash
# Generate the local development keys into ./dev-keys (gitignored).
#
#   internal-jwt.{key,pub}   Ed25519 — the gateway signs internal identity
#                            tokens; every service verifies with the public key.
#   cloudfront.{key,pub}     RSA-2048 — CloudFront signed cookies are specified
#                            as RSA-SHA1, so this one cannot be Ed25519.
#   better-auth.secret       32 random bytes for BetterAuth session signing.
#
# None of these are secrets in any meaningful sense: they are regenerated by
# `make clean` and never leave the machine. On AWS the same paths are mounted
# from Secrets Manager, which is why the services read key *paths* and not key
# *material* from the environment.
set -euo pipefail

KEY_DIR="${KEY_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/dev-keys}"
mkdir -p "$KEY_DIR"
chmod 700 "$KEY_DIR"

generated=0

if [[ ! -f "$KEY_DIR/internal-jwt.key" ]]; then
    openssl genpkey -algorithm ed25519 -out "$KEY_DIR/internal-jwt.key" 2>/dev/null
    openssl pkey -in "$KEY_DIR/internal-jwt.key" -pubout -out "$KEY_DIR/internal-jwt.pub"
    echo "generated internal-jwt keypair (Ed25519)"
    generated=1
fi

if [[ ! -f "$KEY_DIR/cloudfront.key" ]]; then
    openssl genrsa -out "$KEY_DIR/cloudfront.key" 2048 2>/dev/null
    openssl rsa -in "$KEY_DIR/cloudfront.key" -pubout -out "$KEY_DIR/cloudfront.pub" 2>/dev/null
    echo "generated cloudfront cookie-signing keypair (RSA-2048)"
    generated=1
fi

if [[ ! -f "$KEY_DIR/better-auth.secret" ]]; then
    openssl rand -base64 32 | tr -d '\n' > "$KEY_DIR/better-auth.secret"
    echo "generated better-auth secret"
    generated=1
fi

# Readable by the non-root container users (uid 10001 / node).
chmod 644 "$KEY_DIR"/*
chmod 755 "$KEY_DIR"

if [[ "$generated" -eq 0 ]]; then
    echo "dev keys already present in $KEY_DIR (delete the directory to rotate)"
else
    echo "dev keys written to $KEY_DIR"
fi
